### ISSUE TITLE
submit 0.2.0 to CRAN

### ISSUE THREAD

**Issue by markjrieke** [markjrieke/nplyr#16]
- [x] run `devtools::check(remote = TRUE)`
- [x] fix errors
- [x] update to R 4.2.2 & rebuild
- [x] update cran-comments.md

**Comment by markjrieke** [comment]
hey @joranE ! I'm (finally) getting around to merging & submitting version 0.2.0 to CRAN --- once it's accepted, I'll share on twitter/linkedin. Do you have acct's there that I can tag you in? This version was pretty much all you so want to make sure credit goes where it's due!

**Comment by joranE** [comment]
Thanks, that's very kind! I left Twitter for Mastodon recently, actually. I'm @joranelias@mastodon.social over there, and my profile on LinkedIn is www.linkedin.com/in/joran-elias-ab1548255.
