### ISSUE TITLE
nplyr: install ok but error in first GIThub page example...

### ISSUE THREAD

**Issue by sfd99** [markjrieke/nplyr#22]
** Hi Mark -**

Interesting PKG!.
Really want to try it out.

installs OK f/ either CRAN or Github.

But, error
trying the first GIThub page example:

```
gm_nest <- 
    gapminder::gapminder_unfiltered %>%
    tidyr::nest(country_data = -continent)

Error in exists(cacheKey, where = .rs.WorkingDataEnv, inherits = FALSE) : 
  invalid first argument
Error in assign(cacheKey, frame, .rs.CachedDataEnv) : 
  attempt to use zero-length variable name
```

**SFd99
San Francisco
nplyr 0.2.0 latest
R 4.3.1
Rstudio latest
Ubuntu Linux 20.04**

**Comment by markjrieke** [comment]
this looks like an issue with your environment - can you please run an example using a [reprex](https://reprex.tidyverse.org/)?

**Comment by sfd99** [comment]
Ok Mark -
run the reprex: 
> gm_nest <- 
      gapminder::gapminder_unfiltered %>%
      tidyr::nest(country_data = -continent)
Error in exists(cacheKey, where = .rs.WorkingDataEnv, inherits = FALSE) : 
  invalid first argument
Error in assign(cacheKey, frame, .rs.CachedDataEnv) : 
  attempt to use zero-length variable name
> reprex()
ℹ Rendering reprex...
✔ Reprex output is on the clipboard.

MY CLIPBOARD shows:

``` r
gm_nest <- 
    gapminder::gapminder_unfiltered %>%
    tidyr::nest(country_data = -continent)
#> Error in gapminder::gapminder_unfiltered %>% tidyr::nest(country_data = -continent): could not find function "%>%"
```

<sup>Created on 2023-07-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I see above that:
 could not find function "%>%".

Yet... %>% is ok...
> iris %>% class()
[1] "data.frame"

Mystery!
SFd99

**Comment by markjrieke** [comment]
reprex's are self contained environments --- you'll need to call `library(nplyr)` as a part of the reprex

**Comment by sfd99** [comment]
Ah, ok. 
Here is CLPB after running reprex:

``` r
 it 
#> Error in eval(expr, envir, enclos): object 'it' not found
```

<sup>Created on 2023-07-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sfd99** [comment]
BTW:
 the output DF  "gm_nest"
DOES get created (despite the above error msg!):

> gm_nest
# A tibble: 6 × 2
  continent country_data        
  <fct>     <list>              
1 Asia      <tibble [578 × 5]>  
2 Europe    <tibble [1,302 × 5]>
3 Africa    <tibble [637 × 5]>  
4 Americas  <tibble [470 × 5]>  
5 FSU       <tibble [139 × 5]>  
6 Oceania   <tibble [187 × 5]>

**Comment by markjrieke** [comment]
Hi - it looks like you ran a reprex on a single line containing  just `it`, can you please rerun the reprex on the lines of nplyr code you want to diagnose? My assumption is that the issue is with your environment, not with the package, but I'd need to see a reprex to confirm.

**Comment by sfd99** [comment]
Ok - I think everything needed
is now included in the reprex:

```
> library(nplyr)
> 
> gm_nest <-
      gapminder::gapminder_unfiltered %>%
      tidyr::nest(country_data = -continent)
> 
Error in exists(cacheKey, where = .rs.WorkingDataEnv, inherits = FALSE) : 
  invalid first argument
Error in assign(cacheKey, frame, .rs.CachedDataEnv) : 
  attempt to use zero-length variable name
> reprex()
ℹ Removing leading prompts from reprex source.
ℹ Rendering reprex...
Error in parse(text = x, keep.source = TRUE) : 
  <text>:13:13: unexpected symbol
12: # A tibble: 6 × 2
13:   continent country_data
                        ^
> 
```
Mistery!
BUT.... good news!.

Despite the error messg
when creating the gm_nest DF,
The gm_nest DF DOES get created ok...
ALL other examples I tested in the GIT page,
DO work!!!.

So...
it's something on my end.
If I find it -
I will let you know :-).

Meanwhile: 
the nplyr  PKG is GREAT and 100% OPERATIONAL!.
( hey - I can live w/ that ).

Thanks Mark!
**SFd99
San Francisco**
